### ISSUE TITLE
[Question] Where to add omnisharp-extended

### ISSUE THREAD

**Issue by Crashdummyy** [NormalNvim/NormalNvim#384]
Hi there

I'm still struggling to get every C# dotnet stuff to work.
I sometimes cant get this stuff to load

## neotest-dotnet
This had to use a more recent version and the testdiscovery had to be extended.
I got it to work using this but is this the correct file and the correct way to configure it ?

```diff
diff --git a/lua/lazy_snapshot.lua b/lua/lazy_snapshot.lua
index 565be61..2221b77 100644
--- a/lua/lazy_snapshot.lua
+++ b/lua/lazy_snapshot.lua
@@ -1,7 +1,7 @@
 return {
   { "AckslD/nvim-neoclip.lua", commit = "798cd0592a81c185465db3a091a0ff8a21af60fd" },
   { "AstroNvim/astrotheme", version = "^3.4" },
-  { "Issafalcon/neotest-dotnet", commit = "c19df2a139d88c5b4130b830d2cbe63a2c6c6c0c" },
+  { "Issafalcon/neotest-dotnet", version = "*" },
   { "JoosepAlviste/nvim-ts-context-commentstring", commit = "7ab799a9792f7cf3883cf28c6a00ad431f3d382a" },
   { "L3MON4D3/LuaSnip", version = "^3" },
   { "MunifTanjim/nui.nvim", version = "^0.3" },
```

```diff
diff --git a/lua/plugins/3-dev-core.lua b/lua/plugins/3-dev-core.lua
index 71bd605..4e39afd 100644
--- a/lua/plugins/3-dev-core.lua
+++ b/lua/plugins/3-dev-core.lua
@@ -399,6 +415,13 @@ return {
         command = vim.fn.stdpath('data') .. '/mason/bin/netcoredbg',
         args = { '--interpreter=vscode' }
       }
+
+      dap.adapters.netcoredbg = {
+        type = 'executable',
+        command = vim.fn.stdpath('data') .. '/mason/bin/netcoredbg',
+        args = { '--interpreter=vscode' }
+      }
+

@@ -788,7 +838,12 @@ return {
         -- your neotest config here
         adapters = {
           require("neotest-dart"),
-          require("neotest-dotnet"),
+          require("neotest-dotnet") ({
+            dap = {
+              args = { justMyCode = false },
+              adapter_name = "netcoredbg"
+            },
+            discovery_root = "solution" }),
```

## Omnisharp
There are a few things that dont work well with omnisharp and have to be extended

### Autoimports
Namespaces arent automatically imported.
But that most likely is due to [that bug here](https://github.com/OmniSharp/omnisharp-roslyn/issues/2573)

### Omnisharp extended
Some lsp features are still missing and omnisharp-roslyn has to be extended by [omnisharp-extended](https://github.com/Hoffs/omnisharp-extended-lsp.nvim)
I however cant get it to load following https://www.lazyvim.org/extras/lang/omnisharp#nvim-lspconfig

```diff
--- a/lua/plugins/3-dev-core.lua
+++ b/lua/plugins/3-dev-core.lua
@@ -178,6 +178,13 @@ return {
     },
   },
 
+  -- Add extensions to missing omnisharp features
+  -- https://github.com/Hoffs/omnisharp-extended-lsp.nvim
+  {
+    "Hoffs/omnisharp-extended-lsp.nvim",
+    lazy = true
+  },
+
   --  nvim-lspconfig [lsp configs]
   --  https://github.com/neovim/nvim-lspconfig
   --  This plugin provide default configs for the lsp servers available on mason.
@@ -190,7 +197,30 @@ return {
       if utils.is_available("nvim-java") then
         require("lspconfig").jdtls.setup({})
       end
-    end
+    end,
+    opts = {
+      servers = {
+        omnisharp = {
+          handlers = {
+            ["textDocument/definition"] = function(...)
+              return require("omnisharp_extended").handler(...)
+            end,
+          },
+          keys = {
+            {
+              "gd",
+              function()
+                require("omnisharp_extended").telescope_lsp_definitions()
+              end,
+              desc = "Goto Definition",
+            },
+          },
+          enable_roslyn_analyzers = true,
+          organize_imports_on_format = true,
+          enable_import_completion = true,
+        },
+      },
+    },
   },
```

![image](https://github.com/NormalNvim/NormalNvim/assets/15139403/42d9cdc0-69d8-4d4b-9d46-e0fad5d77ab9)

**Comment by Zeioth** [comment]
What has been tested to work with C#:

* formatter
* linter
* compiler
* debuger → I wrote quite complete documentation [here](https://github.com/Zeioth/compiler.nvim/wiki/DAP-support-C%23).
* neotest →  We cannot install it globally for you. You need nunit correctly installed on your csproj file for this to work.

For the missing features you mention, you can try [csharp-language-server](https://github.com/razzmatazz/csharp-language-server) instead of omnisharp. Press Space+p+m, filter the C# language and you can change the LSP server there.

We use omnisharp because it tend to support new .NET versions faster.

About [omnisharp-extended](https://github.com/Hoffs/omnisharp-extended-lsp.nvim) I cannot help because I don't use it sorry. But if you need to add custom LSP handlers, the place to do it is [utils/lsp.lua](https://github.com/NormalNvim/NormalNvim/blob/f5022c2d01e9b01f6877586788ba51df7009f444/lua/base/utils/lsp.lua#L126), which is loaded by the plugin [mason-lspconfig](https://github.com/NormalNvim/NormalNvim/blob/f5022c2d01e9b01f6877586788ba51df7009f444/lua/plugins/3-dev-core.lua#L204). Understanding LSP handlers can be challenging though, so it's better if you can avoid having to touch there.

**Comment by Zeioth** [comment]
Actually I'm reading their docs and it seems they just tell you do use keymappings, so could could modify [the keymappings file](https://github.com/NormalNvim/NormalNvim/blob/f5022c2d01e9b01f6877586788ba51df7009f444/lua/base/4-mappings.lua#L1339) to use the methods provided by that plugin if the filetype csharp.

**Comment by SimonSchwendele** [comment]
> Actually I'm reading their docs and it seems they just tell you do use keymappings, so could could modify [the keymappings file](https://github.com/NormalNvim/NormalNvim/blob/f5022c2d01e9b01f6877586788ba51df7009f444/lua/base/4-mappings.lua#L1339) to use the methods provided by that plugin if the filetype csharp.

Tanks for your reply.
Testing and Debugging works by altering the config like I did.
That was more like a suggestion that the config might be altered to deal with this.

Regarding omnisharp-extended.
I think i might need help on this because I quite dont get it.
I dont know where to put it and it causes weird behavior as well but I think thats omnisharp not working correct.
When I use omnisharp-extended to jump into decompiled code it floods with this:
![image](https://github.com/NormalNvim/NormalNvim/assets/86782769/a8365182-e1f6-475c-9457-69934f66c7d6)

How/where can I put the nnoremaps inside ?
I always get this when I use the documentations samples.
`vim/loader.lua:0: /home/crashdummy/.config/nvim/lua/base/4-mappings.lua:1605: '=' expected near 'gd'`

For now it looks kinda ugly ( like this ):
```diff
@@ -1371,15 +1371,23 @@ function M.lsp_mappings(client, bufnr)
 
   if client.supports_method "textDocument/declaration" then
     lsp_mappings.n["gD"] = {
-      function() vim.lsp.buf.declaration() end,
+      function()
+          vim.lsp.buf.declaration()
+      end,
       desc = "Declaration of current symbol",
     }
   end
 
   if client.supports_method "textDocument/definition" then
     lsp_mappings.n["gd"] = {
-      function() vim.lsp.buf.definition() end,
-      desc = "Show the definition of current symbol",
+        function()
+          if vim.bo.filetype == "cs" then
+            require('omnisharp_extended').lsp_definition()
+          else
+            vim.lsp.buf.definition()
+          end
+        end,
+        desc = "Show the definition of current symbol",
     }
   end
 
@@ -1549,7 +1557,15 @@ function M.lsp_mappings(client, bufnr)
   end
 
   if is_available "telescope.nvim" then -- setup telescope mappings if available
-    if lsp_mappings.n.gd then lsp_mappings.n.gd[1] = function() require("telescope.builtin").lsp_definitions() end end
+    if lsp_mappings.n.gd then lsp_mappings.n.gd[1] =
+      function()
+        if vim.bo.filetype == "cs" then
+          require('omnisharp_extended').telescope_lsp_definition()
+        else
+          require("telescope.builtin").lsp_definitions()
+        end
+      end
+    end
     if lsp_mappings.n.gI then
       lsp_mappings.n.gI[1] = function() require("telescope.builtin").lsp_implementations() end
     end
```


I dont want to use csharp-ls as like you said its way slower to adopt the new dotnet features.
Maybe ms [new lsp](https://github.com/dotnet/vscode-csharp) for vscode might perform better in the feature.
I wish I could do everything in nvim but I still need to use Rider for the blazor development :/
