### ISSUE TITLE
AstroNvim Credits

### ISSUE THREAD

**Issue by mehalter** [NormalNvim/NormalNvim#44]
Hey! I hope all is well and I hope your project is going well! I had a quick request as I've been following this spinning up. I appreciate the credit to AstroNvim that you gave in your README since this is a fork of AstroNvim and built off of it. One thing I noticed is you didn't use the direct fork feature and are not doing merging or cherry picking to keep NormalNvim up to date. AstroNvim has many contributors who put in a lot of effort to maintain the codebase over there and the way you are adding upstream changes removes all of the credit for these code changes. I was just wondering if you would mind using cherry picking or merging or even manually adding co-author statuses to the git commit bodies for when you upstream changes to credit the original contributors on AstroNvim that helped write the code here.

Thanks for your time and consideration!

**Comment by Zeioth** [comment]
That's a great idea. Let me think how I do it. The main reason why the project doesn't appear as a fork on github, even though the distro is openly based on AstroNvim, and incorporates the most important changes from upsteam, is that initially it was going to be for my personal usage, but it kinda evolved in something bigger and I tough it might be of some interest.

If I make it a fork, that's gonna be a cascade of merge conflicts to solve every day, and there is just no way I can keep with it realistically. That's why I'm manually patching the things I find relevant.

Probably in not so long I won't be able to keep up with the pace upstream release updates at all, because I need to find a job, and that's why I'm trying to leave the distro  in an state as stable as possible in the meantime.

My mid term intention right now is to kinda freeze the development soon, incorporating only critical fixes and big features from upstream, and maybe in 1-2 years doing a big re-write and incorporate more stuff from Astro, or other distros (or maybe won't even be necessary, idk atm).

Both projects are GPL3, so crediting the original project should be enough, but I'm totally open to including a credits list section with all the names if there is some way I can get a list of them somehow.

Thank you for reaching me, and I hope I have the chance to cooperate and give back as much as possible, so we can make our users life a bit better together.

Cheers.

**Comment by mehalter** [comment]
Yeah the licensing is definitely permissive for the project and is not the limiting factor here. I just wanted there to be recognition somewhere of the continuing involvement with AstroNvim moving forward. From the README I was unable to tell if it was only originally a fork and now is its own or if it is currently continuing to get code from AstroNvim. Thanks for the consideration. I definitely understand the heavy lifting of adding contributions for each commit/change
